### ISSUE TITLE
Two more integrated circuit bugs

### ISSUE THREAD

**Issue by Eonoc** [BoHBranch/BoH-Bay#500] opened 2020-03-04 01:18 UTC
#### Description of issue
Bug 1: Integrated circuits will delete power cells on removing them. They just cease to exist. Not an invisible sprite or anything, just nonexistant.
Bug 2: Integrated circuit power transmitters of both sizes seem to be working inconsistently.

#### Difference between expected and actual behavior
1. Expected: Remove cell from IC assembly. Get cell in hand or floor. Actual: Click remove, get nothing.
2. Expected: power transmitter smoothly pushes power into attached/internal power cells of devices.
Actual: works far more slowly that it should, requires constant ticking, and often does not work at all, failing to get references for internal batteries.

#### Steps to reproduce
1. Make any IC circuit. Put in any power cell. Click remove next to power cell in interface.
2. Make any of a myriad of circuitry designs that used to work in charging cells inside of other things. Be sad when they don't work, only work on cells on the floor, and charges those excessively slowly.

#### Specific information for locating

https://github.com/BoHBranch/BoH-Bay/tree/8bc68fd6b9e29fdc730ccf6507ea1cecad75ca73/code/modules/integrated_electronics

All under this umbrella, I imagine.
#### Length of time in which bug has been known to occur

At least several weeks.

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: 67eddf5d4a8e15533cf6f941fab409d19f92b2e9 -  - 2020-03-02
Game ID: b5Z-dsbK
Current map: NTSS Dagon

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by MarinaGryphon** [comment] 2020-04-21 04:31
> Expected: power transmitter smoothly pushes power into attached/internal power cells of devices.
Actual: works far more slowly that it should, requires constant ticking, and often does not work at all, failing to get references for internal batteries.
Not a bug. A worthwhile improvement, though.

**Comment by MarinaGryphon** [comment] 2020-04-21 04:31
Duplicate of #173.

**Closed by MarinaGryphon** 2020-04-21 04:31 UTC
Labels: Bug, ✔️Confirmed Bug
