### ISSUE TITLE
Provocatuer blocks any antag recruitment attempts.

### ISSUE THREAD

**Issue by chaoko99** [BoHBranch/BoH-Bay#732] opened 2020-04-23 17:39 UTC
#### Description of issue
See title. Yes it's intended. It's also BAD. esp. for cult.

#### Difference between expected and actual behavior
The opposite of this

#### Steps to reproduce
attempt to recruit any offsite role. Fail

#### Specific information for locating

conversion rune
revolution
diety altar

#### Length of time in which bug has been known to occur

since implementation.

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [x] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/Baystation12/Baystation12/issues)

**Comment by chaoko99** [comment] 2020-04-23 17:39
I hate this  bug skeleton

**Comment by Roland410** [comment] 2020-04-23 19:13
Not a bug, this is intended behavior. All submaps are blacklisted from being antags.

**Comment by chaoko99** [comment] 2020-04-23 19:24
I don't think it's very good that an someone is allowed to jsut go "nuh uh" because they came from someplace outside. It's immulsion breaking and not very rewarding for the antag.

really bad for cult.

**Comment by Roland410** [comment] 2020-04-23 19:36
And what exactly does an off-ship role have to do with a cult on the Dagon? By the way, it is this way because otherwise people on off-ship sites can roll antag, and a traitor colonist is gonna do fuckall to improve a round, and before you say, "but the Dagon can pick them up". At that point it's the same as just spawning on the Dagon as a passenger.

**Comment by chaoko99** [comment] 2020-04-23 22:25
I was thinking of just having Provoc have some special property that makes it good to be replaced. Or something. You *can* have multiple antag datums, but for whatever reason Provoc is a "strong antag" which means it can't be used as a multiple.

Probably because the default value is true.

**Comment by BurgerLUA** [comment] 2020-04-30 22:21
I'm being told it's not a bug and in fact a feature because off-station people shouldn't be getting antag.

**Comment by Roland410** [comment] 2020-06-23 18:58
As per above, closing

**Closed by Roland410** 2020-06-23 18:58 UTC
Labels: 😃Not a Bug
